// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WePass.Infra.Context;

namespace WePass.Infra.Migrations
{
    [DbContext(typeof(WePassContext))]
    [Migration("20200303232620_Evento")]
    partial class Evento
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("WePass.Infra.Entities.Compra", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("Id");

                    b.Property<bool>("Active");

                    b.Property<DateTimeOffset>("CreateDate");

                    b.Property<int>("QuantidadeIngresso");

                    b.Property<DateTimeOffset?>("UpdateDate");

                    b.HasKey("Id")
                        .HasName("Id_Compra");

                    b.ToTable("Compra");
                });

            modelBuilder.Entity("WePass.Infra.Entities.Evento", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("Id");

                    b.Property<bool>("Active");

                    b.Property<string>("Categoria");

                    b.Property<DateTimeOffset>("CreateDate");

                    b.Property<DateTime>("DataEvento");

                    b.Property<string>("NomeEvento");

                    b.Property<DateTimeOffset?>("UpdateDate");

                    b.Property<string>("ValorIngresso");

                    b.Property<int>("quantidadeIngresso");

                    b.HasKey("Id")
                        .HasName("Id_Evento");

                    b.ToTable("Evento");
                });

            modelBuilder.Entity("WePass.Infra.Entities.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("Id");

                    b.Property<bool>("Active");

                    b.Property<string>("Cidade");

                    b.Property<DateTimeOffset>("CreateDate");

                    b.Property<int>("Idade");

                    b.Property<string>("Login");

                    b.Property<string>("Nome");

                    b.Property<string>("Senha");

                    b.Property<DateTimeOffset?>("UpdateDate");

                    b.HasKey("Id")
                        .HasName("Id_Usuario");

                    b.ToTable("Usuario");
                });
#pragma warning restore 612, 618
        }
    }
}
